blank_issues_enabled: true
contact_links:
  - name: "ğŸ’¬ Join Discord"
    about: Chat with us about anything
    url: https://discord.gg/wXy6m2X8wY

  - name: "ğŸŒ Visit Developer Site"
    about: More apps from the developer
    url: https://cssnr.github.io/
